### ISSUE TITLE
ModuleNotFoundError: No module named 'eval_code'

### ISSUE THREAD

**Issue by nihuo76** [JonathonLuiten/HOTA-metrics#1]
Hi, Thank you for sharing your code, it is an amazing work!
Yet when I run the code, I got the following error:
`Traceback (most recent call last):
  File ".\eval_code\Scripts\run_MOTChallenge.py", line 59, in <module>
    from eval_code.Datasets.MOTChallenge_Dataset import load_raw_MOTCha_seq, preproc
ModuleNotFoundError: No module named 'eval_code'`
May I ask the reason?

**Comment by JonathonLuiten** [comment]
The reason is that on your system it doesn't find the correct filepaths in the PYTHONPATH.

Adding these lines: 
```
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
```
to `run_MOTChallenge.py` before the line:
`from eval_code.Datasets.MOTChallenge_Dataset import load_raw_MOTCha_seq, preproc`
should fix the error and find find the correct path on your file system.

Let me know if it works for you before I close this issue. I will add such a line as the default in a future commit.

Jonathon

**Comment by JonathonLuiten** [comment]
This issue no longer occurs with the most recent commit, closing.
